[build]
publish = "public"
command = """\
  curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
  tar -xf dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
  rm dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
  export PATH=/opt/build/repo/dart-sass:$PATH && \
  hugo --gc --minify \
  """

[context.production.environment]
HUGO_VERSION = "0.143.1"
DART_SASS_VERSION = "1.83.4"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.143.1"
DART_SASS_VERSION = "1.83.4"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.143.1"
DART_SASS_VERSION = "1.83.4"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.143.1"
DART_SASS_VERSION = "1.83.4"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/slides"
  to = "/talks"
  status = 301
  force = true

[[redirects]]
  from = "/slides/*"
  to = "https://huijing.github.io/slides/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/demos"
  to = "https://huijing.github.io/demos"
  status = 301
  force = true

[[redirects]]
  from = "/demos/*"
  to = "https://huijing.github.io/demos/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/soundboard"
  to = "https://huijing.github.io/soundboard"
  status = 301
  force = true

[[redirects]]
  from = "/css-property-syntax"
  to = "https://huijing.github.io/css-property-syntax"
  status = 301
  force = true

[[redirects]]
  from = "/css-colours"
  to = "https://huijing.github.io/css-colours"
  status = 301
  force = true

[[redirects]]
  from = "/generic-fonts"
  to = "https://huijing.github.io/generic-fonts"
  status = 301
  force = true

[[redirects]]
  from = "/touch-action"
  to = "https://huijing.github.io/touch-action"
  status = 301
  force = true

[[redirects]]
  from = "/zh-type"
  to = "https://huijing.github.io/zh-type"
  status = 301
  force = true

[[redirects]]
  from = "/html-piano"
  to = "https://huijing.github.io/html-piano"
  status = 301
  force = true

[[redirects]]
  from = "/layouts-demo"
  to = "https://huijing.github.io/layouts-demo"
  status = 301
  force = true
