baseURL: https://chenhuijing.com
languageCode: en
title: Chen Hui Jing
summaryLength: 20

params:
  githubURL: https://huijing.github.io
  description: The chronicles of a self-taught designer and developer.
  images:
  - assets/images/avatar.jpg
  twitter_username: hj_chen
  github_username:  huijing
  mastadon_username: huijing
  about: "I'm Hui Jing, a front-end designer and developer who believes HTML and CSS are the foundation of the web."
  is_playing: 'Final Fantasy XII: The Zodiac Age'
  is_reading: Your Computer Is On Fire
  is_watching: 'The L Word: Generation Q'

permalinks:
  blog: /blog/:slug/

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

taxonomies:
  tag: tags

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: feed

outputs:
  home:
  - HTML
  - RSS
  page:
  - HTML
  section:
  - HTML
  taxonomyTerm:
  - HTML
  taxonomy:
  - HTML
